### ISSUE TITLE
Crashes when opening tweet

### ISSUE THREAD

**Issue by Yowlen** [TwidereProject/Twidere-Android#867]
I sent a couple error reports via Android's built-in reporting system with the feedback "Crashed when opening tweet", and it seems it can be reliably repeated once an affected tweet is found. It seems to be with tweets that contain previewable media (images/videos/article links) that have been retweeted by someone I follow. Also worth noting that this didn't occur in the previous version, so that should help narrow things down.

##Extra Info

Android version: 5.1.1

Network type:

- [X] Cellular
- [X] Wi-Fi

App version: 3.6.19

Build variant:

- [X] Google
- [ ] F-Droid

Micro-blogging service:

- [X] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [X] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [X] Media preview enabled

**Comment by novadeviator** [comment]
I'm hit ny the same bug (or so it seems) with a mastodon post. When the following post appears in the timeline and is taped/clicked to be opened twidere crashes:

https://cybre.space/users/cassolotl/updates/56564

All other toots/tweets with links or media work without problems.

**Comment by mariotaku** [comment]
@novadeviator 3.6.21 should fix this. Try update to newest version?

**Comment by Yowlen** [comment]
Umm, ok, I haven't seen any new version on the Play Store yet, but I did manage to "fix" the issue (though likely only temporary). I cleared the cache & databases within the settings & it works fine now. But I'm guessing it'll pick back up again once the cache or database fills up again until the update becomes available to me.

**Comment by mariotaku** [comment]
@Yowlen This will happen on all retweets IIRC. I think you're able to upgrade to 3.6.21 now since it has been released for hours, and available in every regions.

**Comment by Yowlen** [comment]
Yeah, like I said, it upgraded it for me while I was sleeping & I didn't realize it. The original reply about it still crashing was made after that upgrade to 3.6.21, so the issue still exists in this version.

**Comment by mariotaku** [comment]
@Yowlen So is it still crashing in 3.6.21? I'll check crash reports and see what happens.

**Comment by Yowlen** [comment]
I didn't send any crash reports for 3.6.21 because I didn't know it was a new version until after I had cleared the databases & posted here. I hope the ones I sent from 3.6.19 that I mentioned in the original report are sufficient, since until the database fills up again, I can't send new ones.

**Comment by novadeviator** [comment]
i can confirm that the new version 3.6.21 didn't crash anymore on the above mentioned mastodon toot.
